import { SiteHeader } from "@/components/site-header"
import { Footer } from "@/components/footer"

export default function TermsAndConditionsPage() {
  return (
    <div className="min-h-screen bg-gradient-to-b from-pink-50/50 to-white dark:from-gray-900 dark:to-gray-800 dark:text-white">
      <SiteHeader />

      <main className="container mx-auto px-4 py-16">
        <h1 className="text-4xl font-bold mb-8 text-center">Terms and Conditions</h1>

        <div className="max-w-3xl mx-auto prose dark:prose-invert">
          <h2>1. Acceptance of Terms</h2>
          <p>
            By accessing and using TopMaj AI's website and services, you agree to be bound by these Terms and
            Conditions. If you disagree with any part of these terms, you may not use our services.
          </p>

          <h2>2. Description of Service</h2>
          <p>
            TopMaj AI provides AI-powered fashion design tools, including but not limited to virtual try-ons, AI model
            generation, and trend forecasting. Our services are subject to change or termination at our discretion.
          </p>

          <h2>3. User Accounts</h2>
          <p>
            You are responsible for maintaining the confidentiality of your account and password. You agree to accept
            responsibility for all activities that occur under your account.
          </p>

          <h2>4. Intellectual Property Rights</h2>
          <p>
            4.1. Our Content: The intellectual property rights of all designs, graphics, and AI models generated by
            TopMaj AI remain with us, unless explicitly stated otherwise.
          </p>
          <p>
            4.2. Your Content: You retain the rights to any original content you upload to our platform. By using our
            services, you grant us a license to use, modify, and process your content for the purpose of providing our
            AI-powered services.
          </p>

          <h2>5. AI-Generated Content</h2>
          <p>
            5.1. Ownership: The ownership of AI-generated designs depends on the specific service and subscription plan.
            Please refer to your plan details for specific ownership rights.
          </p>
          <p>
            5.2. Limitations: You acknowledge that AI-generated designs may have limitations and may require human
            refinement or validation before commercial use.
          </p>

          <h2>6. Prohibited Uses</h2>
          <p>
            You must not use TopMaj AI to design or promote any illegal, harmful, or ethically questionable products. We
            reserve the right to terminate accounts that violate this policy.
          </p>

          <h2>7. Disclaimer of Warranties</h2>
          <p>
            TopMaj AI's services are provided "as is" without any warranties, expressed or implied. We do not guarantee
            that our AI-generated designs will be error-free or meet your specific requirements.
          </p>

          <h2>8. Limitation of Liability</h2>
          <p>
            TopMaj AI shall not be liable for any indirect, incidental, special, consequential or punitive damages
            resulting from your use of our services.
          </p>

          <h2>9. Changes to Terms</h2>
          <p>
            We reserve the right to modify these terms at any time. Your continued use of TopMaj AI after changes are
            posted constitutes your acceptance of the modified terms.
          </p>

          <p>
            By using TopMaj AI, you acknowledge that you have read, understood, and agree to be bound by these Terms and
            Conditions.
          </p>
        </div>
      </main>

      <Footer />
    </div>
  )
}
