import { SiteHeader } from "@/components/site-header"
import { Footer } from "@/components/footer"

export default function PrivacyPolicyPage() {
  return (
    <div className="min-h-screen bg-gradient-to-b from-pink-50/50 to-white dark:from-gray-900 dark:to-gray-800 dark:text-white">
      <SiteHeader />

      <main className="container mx-auto px-4 py-16">
        <h1 className="text-4xl font-bold mb-8 text-center">Privacy Policy</h1>

        <div className="max-w-3xl mx-auto prose dark:prose-invert">
          <p>
            This Privacy Policy explains how TopMaj AI ("we", "us", or "our") collects, uses, and protects your personal
            information when you use our AI-powered fashion design platform and services.
          </p>

          <h2>1. Information We Collect</h2>
          <p>We collect and process the following types of information:</p>
          <ul>
            <li>
              Account Information: Name, email address, password, and other details you provide when creating an
              account.
            </li>
            <li>
              Usage Data: Information on how you interact with our platform, including designs created, features used,
              and time spent on the platform.
            </li>
            <li>User Content: Any designs, images, or other content you upload to our platform.</li>
            <li>AI-Generated Content: Designs and other content generated by our AI models based on your inputs.</li>
            <li>
              Payment Information: If you subscribe to a paid plan, we collect payment details through our secure
              payment processors.
            </li>
          </ul>

          <h2>2. How We Use Your Information</h2>
          <p>We use your information to:</p>
          <ul>
            <li>Provide and improve our AI-powered fashion design services.</li>
            <li>Train and enhance our AI models to generate better designs and predictions.</li>
            <li>Personalize your experience on our platform.</li>
            <li>Process payments and manage your account.</li>
            <li>Communicate with you about our services, updates, and offers.</li>
            <li>Analyze usage patterns to improve our platform and services.</li>
          </ul>

          <h2>3. Data Security</h2>
          <p>
            We implement industry-standard security measures to protect your personal information and designs. However,
            no method of transmission over the Internet or electronic storage is 100% secure, so we cannot guarantee
            absolute security.
          </p>

          <h2>4. AI Model Training</h2>
          <p>
            By using our services, you acknowledge and agree that we may use your uploaded content and generated designs
            to train and improve our AI models. We ensure that this process is done in a way that does not expose your
            personal information or specific designs.
          </p>

          <h2>5. Sharing Your Information</h2>
          <p>We do not sell your personal information. We may share your information with:</p>
          <ul>
            <li>Service providers who help us operate our platform and provide our services.</li>
            <li>Legal authorities when required by law or to protect our rights.</li>
            <li>Business partners, with your consent, for specific collaborations or services.</li>
          </ul>

          <h2>6. Your Rights</h2>
          <p>Depending on your location, you may have the right to:</p>
          <ul>
            <li>Access and receive a copy of your personal data.</li>
            <li>Rectify inaccurate personal data.</li>
            <li>Request deletion of your personal data.</li>
            <li>Object to or restrict the processing of your personal data.</li>
            <li>Data portability.</li>
          </ul>

          <h2>7. Cookies and Tracking Technologies</h2>
          <p>
            We use cookies and similar tracking technologies to enhance your experience on our platform. You can manage
            your cookie preferences through your browser settings.
          </p>

          <h2>8. Changes to This Policy</h2>
          <p>
            We may update this Privacy Policy from time to time. We will notify you of any significant changes by
            posting the new Privacy Policy on this page and updating the "Last Updated" date.
          </p>

          <h2>9. Contact Us</h2>
          <p>
            If you have any questions about this Privacy Policy or our data practices, please contact us at
            privacy@topmaj.ai.
          </p>

          <p>Last Updated: [Current Date]</p>
        </div>
      </main>

      <Footer />
    </div>
  )
}
